In [1]:
import math
import numpy as np
import cv2
image = cv2.imread('wp2599594.jpg')
m,n,v = image.shape
gray_image = np.zeros((m,n),np.uint8)
image_onezeroes = np.zeros((m,n),np.uint8)
image_onezeroes2 = np.zeros((m,n),np.uint8)
print(m,n,v)
dummy = 0
for i in range(m):
    for j in range(n):
        for k in range(v):
            dummy = dummy + image[i][j][k]
        gray_image[i][j] = math.floor(dummy/3)
        dummy = 0
for t in range(m):
    for u in range(n):
        image_onezeroes[t][u] = (gray_image[t][u])/255
for v in range(m):
    for w in range(n):
        if(gray_image[v][w] >= 128):
            image_onezeroes2[v][w] = 1
        else:
            image_onezeroes2[v][w] = 0
print("color image pixels")
print(image) 
print("gray image pixels")  
print(gray_image)
print("one/zero image pixels")
print(image_onezeroes)
print("one/zero image2 pixels")
print(image_onezeroes2)

cv2.imshow("original",image)
cv2.waitKey(0)
cv2.imshow('gray',gray_image)
cv2.waitKey(0)
cv2.imshow('zerosones',image_onezeroes)
cv2.waitKey(0)
cv2.imshow('zerosones2',image_onezeroes)
cv2.waitKey(0)
cv2.imshow('grayimage + zerosoneimage ',gray_image + image_onezeroes)
cv2.waitKey(0)
cv2.imshow('grayimage + zerosoneimage2 ',gray_image + image_onezeroes2)
cv2.waitKey(0)
cv2.imshow('grayimage + 20 ',gray_image + 20)
cv2.waitKey(0)
cv2.destroyAllWindows()

1200 1920 3
color image pixels
[[[146 176 193]
  [143 173 190]
  [140 170 187]
  ...
  [170 121  75]
  [171 122  76]
  [176 127  81]]

 [[136 166 183]
  [138 168 185]
  [139 169 186]
  ...
  [166 117  71]
  [167 118  72]
  [172 123  77]]

 [[135 165 182]
  [139 169 186]
  [142 172 189]
  ...
  [163 114  68]
  [165 116  70]
  [170 121  75]]

 ...

 [[ 61  95 111]
  [ 50  84 100]
  [ 48  82  98]
  ...
  [ 48  79 100]
  [ 50  81 102]
  [ 53  84 105]]

 [[ 31  65  81]
  [ 21  55  71]
  [ 19  53  69]
  ...
  [ 35  66  89]
  [ 63  94 117]
  [ 47  78 101]]

 [[ 36  70  86]
  [ 36  70  86]
  [ 47  81  97]
  ...
  [ 36  67  90]
  [ 37  68  91]
  [ 58  89 112]]]
gray image pixels
[[171 168 165 ... 122 123 128]
 [161 163 164 ... 118 119 124]
 [160 164 167 ... 115 117 122]
 ...
 [ 89  78  76 ...  75  77  80]
 [ 59  49  47 ...  63  91  75]
 [ 64  64  75 ...  64  65  86]]
one/zero image pixels
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0